modLoader="javafml"
loaderVersion="[4,)"
license="GPL-3.0"
issueTrackerURL="https://github.com/retrooper/packetevents/issues"

[[mods]]
modId="packetevents"
version="${version}"
displayName="PacketEvents"
displayURL="https://github.com/retrooper/packetevents"
logoFile="assets/packetevents/icon.png"
authors="retrooper, booky10"
description=""

[[dependencies.packetevents]]
modId="neoforge"
type="required"
versionRange="[21.9.15-beta,)"
ordering="NONE"
side="BOTH"

[[dependencies.packetevents]]
modId="minecraft"
type="required"
versionRange="[26.2,26.3)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="packetevents.mixins.json"